name: Final Project Code Coverage

on:
  push:
    branches:
      - main

jobs:
  test_Dual:
    name: test code implementation (milestone2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # let's use a recent version
      - name: Install dependencies
        run: python -m pip install pytest pytest-cov
      - name: Run test suite and generate coverage report
        run: cd tests && ./run_tests.sh pytest --cov=pomeranian --cov-report=html:htmlcov
      - name: Clean .gitignore in coverage output
        run: rm -f tests/htmlcov/.gitignore
      - name: Deploy test coverage to GitHub page (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tests/htmlcov # The folder the action should deploy.
      - name: Determine whether the coverage reaches the specific 
        run: ./tests/check_coverage.sh


