name: Final Project Tests
on:
  push:
    branches:
      - main

jobs:
  test_Dual:
    name: test code implementation (milestone2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # let's use a recent version
      - name: Install dependencies
        run: python -m pip install pytest pytest-cov
      - name: Run test suite
        run: cd tests && ./run_tests.sh pytest


